# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install
      - run: yarn build
      - run:
          background: true
          command: ./node_modules/.bin/http-server build
          
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      - run: unzip ngrok-stable-linux-amd64.zip
      - run: chmod +x ngrok
      - run: ./ngrok authtoken ${NGROK_TOKEN}
      - run:
          background: true
          # stdout of this: https://github.com/inconshreveable/ngrok/issues/57
          command: ./ngrok http 8080 -log=stdout
      - run: sleep 60